-- MySQL Script generated by MySQL Workbench
-- Wed Nov  7 16:40:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CST8257
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CST8257` ;

-- -----------------------------------------------------
-- Schema CST8257
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CST8257` DEFAULT CHARACTER SET utf8 ;
USE `CST8257` ;

-- -----------------------------------------------------
-- Table `CST8257`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CST8257`.`Student` ;

CREATE TABLE IF NOT EXISTS `CST8257`.`Student` (
  `StudentId` VARCHAR(16) NOT NULL,
  `Name` VARCHAR(256) NOT NULL,
  `Phone` VARCHAR(16) NULL,
  `Pasword` VARCHAR(256) NULL,
  PRIMARY KEY (`StudentId`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `CST8257`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CST8257`.`Course` ;

CREATE TABLE IF NOT EXISTS `CST8257`.`Course` (
  `CourseCode` VARCHAR(10) NOT NULL,
  `Title` VARCHAR(256) NOT NULL,
  `WeeklyHours` INT NOT NULL,
  PRIMARY KEY (`CourseCode`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `CST8257`.`Semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CST8257`.`Semester` ;

CREATE TABLE IF NOT EXISTS `CST8257`.`Semester` (
  `SemesterCode` VARCHAR(10) NOT NULL,
  `Year` INT NOT NULL,
  `Term` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`SemesterCode`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `CST8257`.`CourseOffer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CST8257`.`CourseOffer` ;

CREATE TABLE IF NOT EXISTS `CST8257`.`CourseOffer` (
  `CourseCode` VARCHAR(10) NOT NULL,
  `SemesterCode` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`CourseCode`, `SemesterCode`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `CST8257`.`Registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CST8257`.`Registration` ;

CREATE TABLE IF NOT EXISTS `CST8257`.`Registration` (
  `StudentId` VARCHAR(16) NOT NULL,
  `CourseCode` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`StudentId`, `CourseCode`))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
